channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia

dependencies:
  - python=3.11
  - pytorch::pytorch=2.2.*
  - pytorch::pytorch-cuda=11.8.0
  - lightning=2.2.*
  - torchmetrics=1.3.*
  - hydra-core=1.3.*
  - hydra-colorlog=1.2.*
  - rich=13.7.*
  - pre-commit=3.7.*
  - pytest=8.1.*
  - wandb=0.16.*
  - transformers=4.39.*
  - datasets=2.18.*
  - sentencepiece=0.2.*
  - gradio=4.26.*
  - huggingface_hub=0.22.*
  - ipykernel=6.29.*
  - ipywidgets=8.1.*

  - pip>=24
  - pip:
      - hydra-optuna-sweeper
      - rootutils
