_target_: src.models.t5_module.T5FineTunerLitModule
model_name: google/byt5-small
max_length: 512

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

arabic_only: true
include_no_diacritic: true

# compile model for faster training with pytorch 2.0
compile: false
